// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDMz--9nuKG5QQgpRjs2W5ltiVjyWbh9-Y',
    appId: '1:368817648784:web:c6458e462f182d7fca5415',
    messagingSenderId: '368817648784',
    projectId: 'haya-vehicle-check-up',
    authDomain: 'haya-vehicle-check-up.firebaseapp.com',
    storageBucket: 'haya-vehicle-check-up.firebasestorage.app',
    measurementId: 'G-Y2JLYVJGX3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCoH6aNJyFcxdihjw_Nch8cBGh23zBCwfE',
    appId: '1:368817648784:android:10f445f7763f181eca5415',
    messagingSenderId: '368817648784',
    projectId: 'haya-vehicle-check-up',
    storageBucket: 'haya-vehicle-check-up.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB5wXyNH4qLbqy6HyM_JJroBBfn1YEJunE',
    appId: '1:368817648784:ios:87405aeda32bdccdca5415',
    messagingSenderId: '368817648784',
    projectId: 'haya-vehicle-check-up',
    storageBucket: 'haya-vehicle-check-up.firebasestorage.app',
    iosBundleId: 'com.example.vehicleCheckup',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB5wXyNH4qLbqy6HyM_JJroBBfn1YEJunE',
    appId: '1:368817648784:ios:87405aeda32bdccdca5415',
    messagingSenderId: '368817648784',
    projectId: 'haya-vehicle-check-up',
    storageBucket: 'haya-vehicle-check-up.firebasestorage.app',
    iosBundleId: 'com.example.vehicleCheckup',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCRchrJuPV2BHOO3r2MvTrU8kizqU_7J4M',
    appId: '1:368817648784:web:4cc1c654e8478cb5ca5415',
    messagingSenderId: '368817648784',
    projectId: 'haya-vehicle-check-up',
    authDomain: 'haya-vehicle-check-up.firebaseapp.com',
    storageBucket: 'haya-vehicle-check-up.firebasestorage.app',
    measurementId: 'G-Q8EKLNTE3W',
  );
}
